# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - 'last 2 versions'
  - 'ie >= 9'
  - 'ios >= 7'

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - 'src/**/*.html'
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: 'dist'
  distProject: '../BritboxWebsite/Content'
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - 'src/assets/**/*'
    - '!src/assets/{img,js,scss}/**/*'
  # Path to icons font generator
  assetsIcons:
    - 'src/assets/icons/*.svg'
  assetsFonts:
    - 'src/assets/fonts'
  assetsDist:
    - 'dist/assets/{img,fonts,icons,animations}/**/*'
    - '!dist/assets/img/flags/**'
    - '!dist/assets/img/static/**'
    # - 'dist/assets/{img,js,css,videos,fonts}/**/*'
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - 'node_modules/foundation-sites/scss'
    - 'node_modules/motion-ui/src'
    - 'node_modules/bourbon/core'
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - 'src/assets/js/lib/polyfill.js'
    - 'src/assets/js/*.js'
  entriesJs:
    - 'src/assets/js/lib/polyfill.js'
    - 'dist/assets/js/*.js'
  entriesCss:
    - 'dist/assets/css/*.css'
  entriesvendor:
    - 'src/assets/js/lib/polyfill.js'
    - 'node_modules/jquery/dist/jquery.min.js'
    # - 'node_modules/cash-dom/dist/cash.min.js'
    - 'node_modules/jquery-ui-bundle/jquery-ui.min.js'
    - 'node_modules/nouislider/distribute/nouislider.min.js'
    - 'node_modules/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js'
    - 'node_modules/gasparesganga-jquery-loading-overlay/dist/loadingoverlay.min.js'
    - 'node_modules/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js'
    - 'src/assets/js/lib/autocomplete.js'
    - 'src/assets/js/lib/jquery.tmpl.js'
    - 'src/assets/js/lib/jquery.initialize.js'
