/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * BRITBOX SEARCH API - 1.0
 * BRITBOX SEARCH API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


import * as url from "url";
import * as portableFetch from "portable-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "https://staging-api.britbox.takeoffmedia.com/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = portableFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
};

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name: "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 *
 * @export
 * @interface BritboxAPISearchModelsSearchGetResponse
 */
export interface BritboxAPISearchModelsSearchGetResponse {
    /**
     *
     * @type {MassiveSDKModelSearchResults}
     * @memberof BritboxAPISearchModelsSearchGetResponse
     */
    externalResponse?: MassiveSDKModelSearchResults;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof BritboxAPISearchModelsSearchGetResponse
     */
    errors?: Array<string>;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof BritboxAPISearchModelsSearchGetResponse
     */
    messages?: Array<string>;
}

/**
 *
 * @export
 * @interface MassiveSDKModelClassification
 */
export interface MassiveSDKModelClassification {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelClassification
     */
    code?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelClassification
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelClassification
     */
    advisoryText?: string;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelClassification
     */
    level?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelClassification
     */
    system?: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof MassiveSDKModelClassification
     */
    images?: { [key: string]: string; };
}

/**
 *
 * @export
 * @interface MassiveSDKModelClassificationSummary
 */
export interface MassiveSDKModelClassificationSummary {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelClassificationSummary
     */
    code?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelClassificationSummary
     */
    name?: string;
}

/**
 *
 * @export
 * @interface MassiveSDKModelContinueWatchingListData
 */
export interface MassiveSDKModelContinueWatchingListData {
    /**
     *
     * @type {{ [key: string]: MassiveSDKModelContinueWatchingListDataExpansion; }}
     * @memberof MassiveSDKModelContinueWatchingListData
     */
    itemInclusions?: { [key: string]: MassiveSDKModelContinueWatchingListDataExpansion; };
}

/**
 *
 * @export
 * @interface MassiveSDKModelContinueWatchingListDataExpansion
 */
export interface MassiveSDKModelContinueWatchingListDataExpansion {
    /**
     *
     * @type {MassiveSDKModelItemSummary}
     * @memberof MassiveSDKModelContinueWatchingListDataExpansion
     */
    episode?: MassiveSDKModelItemSummary;
    /**
     *
     * @type {MassiveSDKModelItemSummary}
     * @memberof MassiveSDKModelContinueWatchingListDataExpansion
     */
    season?: MassiveSDKModelItemSummary;
    /**
     *
     * @type {MassiveSDKModelItemSummary}
     * @memberof MassiveSDKModelContinueWatchingListDataExpansion
     */
    show?: MassiveSDKModelItemSummary;
}

/**
 *
 * @export
 * @interface MassiveSDKModelCredit
 */
export interface MassiveSDKModelCredit {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelCredit
     */
    role?: MassiveSDKModelCredit.RoleEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelCredit
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelCredit
     */
    path?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelCredit
     */
    character?: string;
}

/**
 * @export
 * @namespace MassiveSDKModelCredit
 */
export namespace MassiveSDKModelCredit {
    /**
     * @export
     * @enum {string}
     */
    export enum RoleEnum {
        Actor = <any> 'actor',
        Associateproducer = <any> 'associateproducer',
        Coactor = <any> 'coactor',
        Director = <any> 'director',
        Executiveproducer = <any> 'executiveproducer',
        Filminglocation = <any> 'filminglocation',
        Guest = <any> 'guest',
        Narrator = <any> 'narrator',
        Other = <any> 'other',
        Presenter = <any> 'presenter',
        Producer = <any> 'producer',
        Productmanager = <any> 'productmanager',
        Thememusicby = <any> 'thememusicby',
        Voice = <any> 'voice',
        Writer = <any> 'writer'
    }
}

/**
 *
 * @export
 * @interface MassiveSDKModelEpisodes
 */
export interface MassiveSDKModelEpisodes {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodes
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodes
     */
    path?: string;
    /**
     *
     * @type {Array&lt;MassiveSDKModelEpisodesItem&gt;}
     * @memberof MassiveSDKModelEpisodes
     */
    items?: Array<MassiveSDKModelEpisodesItem>;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelEpisodes
     */
    size?: number;
    /**
     *
     * @type {MassiveSDKModelPaging}
     * @memberof MassiveSDKModelEpisodes
     */
    paging?: MassiveSDKModelPaging;
}

/**
 *
 * @export
 * @interface MassiveSDKModelEpisodesItem
 */
export interface MassiveSDKModelEpisodesItem {
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof MassiveSDKModelEpisodesItem
     */
    images?: { [key: string]: string; };
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelEpisodesItem
     */
    duration?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelEpisodesItem
     */
    releaseYear?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelEpisodesItem
     */
    episodeNumber?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    episodeName?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    seasonId?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    showId?: string;
    /**
     *
     * @type {Array&lt;MassiveSDKModelOffer&gt;}
     * @memberof MassiveSDKModelEpisodesItem
     */
    offers?: Array<MassiveSDKModelOffer>;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelEpisodesItem
     */
    scopes?: Array<string>;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelEpisodesItem
     */
    categories?: Array<string>;
    /**
     *
     * @type {any}
     * @memberof MassiveSDKModelEpisodesItem
     */
    customFields?: any;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    customId?: string;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelEpisodesItem
     */
    genres?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    type?: string;
    /**
     *
     * @type {Date}
     * @memberof MassiveSDKModelEpisodesItem
     */
    maximumOfferEnd?: Date;
    /**
     *
     * @type {Array&lt;MassiveSDKModelMedia&gt;}
     * @memberof MassiveSDKModelEpisodesItem
     */
    media?: Array<MassiveSDKModelMedia>;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    shortDescription?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    contextualTitle?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    title?: string;
    /**
     *
     * @type {MassiveSDKModelClassification}
     * @memberof MassiveSDKModelEpisodesItem
     */
    classification?: MassiveSDKModelClassification;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelEpisodesItem
     */
    totalUserRatings?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    path?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    watchPath?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    showTitle?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelEpisodesItem
     */
    seasonTitle?: string;
}

/**
 *
 * @export
 * @interface MassiveSDKModelExclusionRule
 */
export interface MassiveSDKModelExclusionRule {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelExclusionRule
     */
    excludeDelivery?: MassiveSDKModelExclusionRule.ExcludeDeliveryEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelExclusionRule
     */
    excludeMinResolution?: MassiveSDKModelExclusionRule.ExcludeMinResolutionEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelExclusionRule
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelExclusionRule
     */
    device?: string;
    /**
     *
     * @type {boolean}
     * @memberof MassiveSDKModelExclusionRule
     */
    excludeAirplay?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof MassiveSDKModelExclusionRule
     */
    excludeChromecast?: boolean;
}

/**
 * @export
 * @namespace MassiveSDKModelExclusionRule
 */
export namespace MassiveSDKModelExclusionRule {
    /**
     * @export
     * @enum {string}
     */
    export enum ExcludeDeliveryEnum {
        Stream = <any> 'Stream',
        Download = <any> 'Download',
        StreamOrDownload = <any> 'StreamOrDownload',
        ProgressiveDownload = <any> 'ProgressiveDownload',
        None = <any> 'None'
    }
    /**
     * @export
     * @enum {string}
     */
    export enum ExcludeMinResolutionEnum {
        SD = <any> 'SD',
        HD720 = <any> 'HD-720',
        HD1080 = <any> 'HD-1080',
        HD4K = <any> 'HD-4K',
        External = <any> 'External',
        Unknown = <any> 'Unknown'
    }
}

/**
 *
 * @export
 * @interface MassiveSDKModelItemList
 */
export interface MassiveSDKModelItemList {
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelItemList
     */
    itemTypes?: Array<MassiveSDKModelItemList.ItemTypesEnum>;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemList
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemList
     */
    title?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemList
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemList
     */
    shortDescription?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemList
     */
    tagline?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemList
     */
    path?: string;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelItemList
     */
    size?: number;
    /**
     *
     * @type {Array&lt;MassiveSDKModelItemSummary&gt;}
     * @memberof MassiveSDKModelItemList
     */
    items?: Array<MassiveSDKModelItemSummary>;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof MassiveSDKModelItemList
     */
    images?: { [key: string]: string; };
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemList
     */
    parameter?: string;
    /**
     *
     * @type {MassiveSDKModelPagination}
     * @memberof MassiveSDKModelItemList
     */
    paging?: MassiveSDKModelPagination;
    /**
     *
     * @type {any}
     * @memberof MassiveSDKModelItemList
     */
    customFields?: any;
    /**
     *
     * @type {Array&lt;MassiveSDKModelTheme&gt;}
     * @memberof MassiveSDKModelItemList
     */
    themes?: Array<MassiveSDKModelTheme>;
    /**
     *
     * @type {MassiveSDKModelListData}
     * @memberof MassiveSDKModelItemList
     */
    listData?: MassiveSDKModelListData;
}

/**
 * @export
 * @namespace MassiveSDKModelItemList
 */
export namespace MassiveSDKModelItemList {
    /**
     * @export
     * @enum {string}
     */
    export enum ItemTypesEnum {
        Movie = <any> 'movie',
        Show = <any> 'show',
        Season = <any> 'season',
        Episode = <any> 'episode',
        Program = <any> 'program',
        Link = <any> 'link',
        Trailer = <any> 'trailer',
        Channel = <any> 'channel',
        CustomAsset = <any> 'customAsset'
    }
}

/**
 *
 * @export
 * @interface MassiveSDKModelItemSummary
 */
export interface MassiveSDKModelItemSummary {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    type?: MassiveSDKModelItemSummary.TypeEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    subtype?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    title?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    contextualTitle?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    shortDescription?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    tagline?: string;
    /**
     *
     * @type {MassiveSDKModelClassificationSummary}
     * @memberof MassiveSDKModelItemSummary
     */
    classification?: MassiveSDKModelClassificationSummary;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    path?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    watchPath?: string;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelItemSummary
     */
    scopes?: Array<string>;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelItemSummary
     */
    releaseYear?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelItemSummary
     */
    episodeCount?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelItemSummary
     */
    availableEpisodeCount?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelItemSummary
     */
    availableSeasonCount?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelItemSummary
     */
    seasonNumber?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelItemSummary
     */
    episodeNumber?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    episodeName?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    showId?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    showTitle?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    seasonId?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    seasonTitle?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    channelShortCode?: string;
    /**
     *
     * @type {boolean}
     * @memberof MassiveSDKModelItemSummary
     */
    hasClosedCaptions?: boolean;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelItemSummary
     */
    averageUserRating?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    badge?: string;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelItemSummary
     */
    genres?: Array<string>;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelItemSummary
     */
    duration?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelItemSummary
     */
    customId?: string;
    /**
     *
     * @type {Array&lt;MassiveSDKModelOffer&gt;}
     * @memberof MassiveSDKModelItemSummary
     */
    offers?: Array<MassiveSDKModelOffer>;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof MassiveSDKModelItemSummary
     */
    images?: { [key: string]: string; };
    /**
     *
     * @type {Array&lt;MassiveSDKModelTheme&gt;}
     * @memberof MassiveSDKModelItemSummary
     */
    themes?: Array<MassiveSDKModelTheme>;
    /**
     *
     * @type {any}
     * @memberof MassiveSDKModelItemSummary
     */
    customFields?: any;
    /**
     *
     * @type {MassiveSDKModelShow}
     * @memberof MassiveSDKModelItemSummary
     */
    show?: MassiveSDKModelShow;
    /**
     *
     * @type {MassiveSDKModelEpisodes}
     * @memberof MassiveSDKModelItemSummary
     */
    episodes?: MassiveSDKModelEpisodes;
    /**
     *
     * @type {MassiveSDKModelItemSummary}
     * @memberof MassiveSDKModelItemSummary
     */
    season?: MassiveSDKModelItemSummary;
    /**
     *
     * @type {Array&lt;MassiveSDKModelCredit&gt;}
     * @memberof MassiveSDKModelItemSummary
     */
    credits?: Array<MassiveSDKModelCredit>;
}

/**
 * @export
 * @namespace MassiveSDKModelItemSummary
 */
export namespace MassiveSDKModelItemSummary {
    /**
     * @export
     * @enum {string}
     */
    export enum TypeEnum {
        Movie = <any> 'movie',
        Show = <any> 'show',
        Season = <any> 'season',
        Episode = <any> 'episode',
        Program = <any> 'program',
        Link = <any> 'link',
        Trailer = <any> 'trailer',
        Channel = <any> 'channel',
        CustomAsset = <any> 'customAsset'
    }
}

/**
 *
 * @export
 * @interface MassiveSDKModelListData
 */
export interface MassiveSDKModelListData {
    /**
     *
     * @type {MassiveSDKModelContinueWatchingListData}
     * @memberof MassiveSDKModelListData
     */
    continueWatching?: MassiveSDKModelContinueWatchingListData;
}

/**
 *
 * @export
 * @interface MassiveSDKModelMedia
 */
export interface MassiveSDKModelMedia {
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelMedia
     */
    duration?: number;
}

/**
 *
 * @export
 * @interface MassiveSDKModelOffer
 */
export interface MassiveSDKModelOffer {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelOffer
     */
    deliveryType?: MassiveSDKModelOffer.DeliveryTypeEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelOffer
     */
    resolution?: MassiveSDKModelOffer.ResolutionEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelOffer
     */
    ownership?: MassiveSDKModelOffer.OwnershipEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelOffer
     */
    availability?: MassiveSDKModelOffer.AvailabilityEnum;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelOffer
     */
    scopes?: Array<string>;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelOffer
     */
    maxPlays?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelOffer
     */
    maxDownloads?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelOffer
     */
    rentalPeriod?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelOffer
     */
    playPeriod?: number;
    /**
     *
     * @type {Array&lt;MassiveSDKModelExclusionRule&gt;}
     * @memberof MassiveSDKModelOffer
     */
    exclusionRules?: Array<MassiveSDKModelExclusionRule>;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelOffer
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelOffer
     */
    name?: string;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelOffer
     */
    price?: number;
    /**
     *
     * @type {Date}
     * @memberof MassiveSDKModelOffer
     */
    startDate?: Date;
    /**
     *
     * @type {Date}
     * @memberof MassiveSDKModelOffer
     */
    endDate?: Date;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelOffer
     */
    subscriptionCode?: string;
    /**
     *
     * @type {any}
     * @memberof MassiveSDKModelOffer
     */
    customFields?: any;
}

/**
 * @export
 * @namespace MassiveSDKModelOffer
 */
export namespace MassiveSDKModelOffer {
    /**
     * @export
     * @enum {string}
     */
    export enum DeliveryTypeEnum {
        Stream = <any> 'Stream',
        Download = <any> 'Download',
        StreamOrDownload = <any> 'StreamOrDownload',
        ProgressiveDownload = <any> 'ProgressiveDownload',
        None = <any> 'None'
    }
    /**
     * @export
     * @enum {string}
     */
    export enum ResolutionEnum {
        SD = <any> 'SD',
        HD720 = <any> 'HD-720',
        HD1080 = <any> 'HD-1080',
        HD4K = <any> 'HD-4K',
        External = <any> 'External',
        Unknown = <any> 'Unknown'
    }
    /**
     * @export
     * @enum {string}
     */
    export enum OwnershipEnum {
        Subscription = <any> 'Subscription',
        Free = <any> 'Free',
        Rent = <any> 'Rent',
        Own = <any> 'Own',
        None = <any> 'None'
    }
    /**
     * @export
     * @enum {string}
     */
    export enum AvailabilityEnum {
        Available = <any> 'Available',
        ComingSoon = <any> 'ComingSoon'
    }
}

/**
 *
 * @export
 * @interface MassiveSDKModelOptions
 */
export interface MassiveSDKModelOptions {
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelOptions
     */
    pageSize?: number;
}

/**
 *
 * @export
 * @interface MassiveSDKModelPagination
 */
export interface MassiveSDKModelPagination {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPagination
     */
    next?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPagination
     */
    previous?: string;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelPagination
     */
    page?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelPagination
     */
    size?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelPagination
     */
    total?: number;
    /**
     *
     * @type {MassiveSDKModelPaginationAuth}
     * @memberof MassiveSDKModelPagination
     */
    authorization?: MassiveSDKModelPaginationAuth;
    /**
     *
     * @type {MassiveSDKModelPaginationOptions}
     * @memberof MassiveSDKModelPagination
     */
    options?: MassiveSDKModelPaginationOptions;
}

/**
 *
 * @export
 * @interface MassiveSDKModelPaginationAuth
 */
export interface MassiveSDKModelPaginationAuth {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPaginationAuth
     */
    type?: MassiveSDKModelPaginationAuth.TypeEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPaginationAuth
     */
    scope?: MassiveSDKModelPaginationAuth.ScopeEnum;
}

/**
 * @export
 * @namespace MassiveSDKModelPaginationAuth
 */
export namespace MassiveSDKModelPaginationAuth {
    /**
     * @export
     * @enum {string}
     */
    export enum TypeEnum {
        UserAccount = <any> 'UserAccount',
        UserProfile = <any> 'UserProfile'
    }
    /**
     * @export
     * @enum {string}
     */
    export enum ScopeEnum {
        Catalog = <any> 'Catalog',
        Commerce = <any> 'Commerce',
        Settings = <any> 'Settings'
    }
}

/**
 *
 * @export
 * @interface MassiveSDKModelPaginationOptions
 */
export interface MassiveSDKModelPaginationOptions {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPaginationOptions
     */
    order?: MassiveSDKModelPaginationOptions.OrderEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPaginationOptions
     */
    orderBy?: MassiveSDKModelPaginationOptions.OrderByEnum;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPaginationOptions
     */
    itemType?: MassiveSDKModelPaginationOptions.ItemTypeEnum;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelPaginationOptions
     */
    pageSize?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPaginationOptions
     */
    maxRating?: string;
    /**
     *
     * @type {boolean}
     * @memberof MassiveSDKModelPaginationOptions
     */
    completed?: boolean;
}

/**
 * @export
 * @namespace MassiveSDKModelPaginationOptions
 */
export namespace MassiveSDKModelPaginationOptions {
    /**
     * @export
     * @enum {string}
     */
    export enum OrderEnum {
        Asc = <any> 'asc',
        Desc = <any> 'desc'
    }
    /**
     * @export
     * @enum {string}
     */
    export enum OrderByEnum {
        AZ = <any> 'a-z',
        ReleaseYear = <any> 'release-year',
        DateAdded = <any> 'date-added'
    }
    /**
     * @export
     * @enum {string}
     */
    export enum ItemTypeEnum {
        Movie = <any> 'movie',
        Show = <any> 'show',
        Season = <any> 'season',
        Episode = <any> 'episode',
        Program = <any> 'program',
        Link = <any> 'link',
        Trailer = <any> 'trailer',
        Channel = <any> 'channel',
        CustomAsset = <any> 'customAsset'
    }
}

/**
 *
 * @export
 * @interface MassiveSDKModelPaging
 */
export interface MassiveSDKModelPaging {
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelPaging
     */
    total?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelPaging
     */
    page?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelPaging
     */
    size?: number;
    /**
     *
     * @type {MassiveSDKModelOptions}
     * @memberof MassiveSDKModelPaging
     */
    options?: MassiveSDKModelOptions;
}

/**
 *
 * @export
 * @interface MassiveSDKModelPerson
 */
export interface MassiveSDKModelPerson {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPerson
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelPerson
     */
    path?: string;
}

/**
 *
 * @export
 * @interface MassiveSDKModelSearchResults
 */
export interface MassiveSDKModelSearchResults {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSearchResults
     */
    term?: string;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelSearchResults
     */
    total?: number;
    /**
     *
     * @type {MassiveSDKModelItemList}
     * @memberof MassiveSDKModelSearchResults
     */
    items?: MassiveSDKModelItemList;
    /**
     *
     * @type {MassiveSDKModelItemList}
     * @memberof MassiveSDKModelSearchResults
     */
    movies?: MassiveSDKModelItemList;
    /**
     *
     * @type {MassiveSDKModelItemList}
     * @memberof MassiveSDKModelSearchResults
     */
    tv?: MassiveSDKModelItemList;
    /**
     *
     * @type {MassiveSDKModelItemList}
     * @memberof MassiveSDKModelSearchResults
     */
    other?: MassiveSDKModelItemList;
    /**
     *
     * @type {Array&lt;MassiveSDKModelPerson&gt;}
     * @memberof MassiveSDKModelSearchResults
     */
    people?: Array<MassiveSDKModelPerson>;
}

/**
 *
 * @export
 * @interface MassiveSDKModelSeasons
 */
export interface MassiveSDKModelSeasons {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasons
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasons
     */
    path?: string;
    /**
     *
     * @type {Array&lt;MassiveSDKModelSeasonsItem&gt;}
     * @memberof MassiveSDKModelSeasons
     */
    items?: Array<MassiveSDKModelSeasonsItem>;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelSeasons
     */
    size?: number;
    /**
     *
     * @type {MassiveSDKModelPaging}
     * @memberof MassiveSDKModelSeasons
     */
    paging?: MassiveSDKModelPaging;
}

/**
 *
 * @export
 * @interface MassiveSDKModelSeasonsItem
 */
export interface MassiveSDKModelSeasonsItem {
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof MassiveSDKModelSeasonsItem
     */
    images?: { [key: string]: string; };
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelSeasonsItem
     */
    releaseYear?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelSeasonsItem
     */
    availableEpisodeCount?: number;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelSeasonsItem
     */
    seasonNumber?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasonsItem
     */
    showId?: string;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelSeasonsItem
     */
    episodeCount?: number;
    /**
     *
     * @type {Array&lt;MassiveSDKModelOffer&gt;}
     * @memberof MassiveSDKModelSeasonsItem
     */
    offers?: Array<MassiveSDKModelOffer>;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelSeasonsItem
     */
    scopes?: Array<string>;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelSeasonsItem
     */
    categories?: Array<string>;
    /**
     *
     * @type {any}
     * @memberof MassiveSDKModelSeasonsItem
     */
    customFields?: any;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasonsItem
     */
    customId?: string;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelSeasonsItem
     */
    genres?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasonsItem
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasonsItem
     */
    type?: string;
    /**
     *
     * @type {Date}
     * @memberof MassiveSDKModelSeasonsItem
     */
    maximumOfferEnd?: Date;
    /**
     *
     * @type {Array&lt;any&gt;}
     * @memberof MassiveSDKModelSeasonsItem
     */
    media?: Array<any>;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasonsItem
     */
    shortDescription?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasonsItem
     */
    contextualTitle?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasonsItem
     */
    title?: string;
    /**
     *
     * @type {MassiveSDKModelClassification}
     * @memberof MassiveSDKModelSeasonsItem
     */
    classification?: MassiveSDKModelClassification;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelSeasonsItem
     */
    totalUserRatings?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasonsItem
     */
    path?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelSeasonsItem
     */
    showTitle?: string;
}

/**
 *
 * @export
 * @interface MassiveSDKModelShow
 */
export interface MassiveSDKModelShow {
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof MassiveSDKModelShow
     */
    images?: { [key: string]: string; };
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    advisoryText?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    copyright?: string;
    /**
     *
     * @type {Array&lt;MassiveSDKModelCredit&gt;}
     * @memberof MassiveSDKModelShow
     */
    credits?: Array<MassiveSDKModelCredit>;
    /**
     *
     * @type {Array&lt;any&gt;}
     * @memberof MassiveSDKModelShow
     */
    customMetadata?: Array<any>;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    distributor?: string;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelShow
     */
    availableSeasonCount?: number;
    /**
     *
     * @type {Array&lt;MassiveSDKModelOffer&gt;}
     * @memberof MassiveSDKModelShow
     */
    offers?: Array<MassiveSDKModelOffer>;
    /**
     *
     * @type {Array&lt;any&gt;}
     * @memberof MassiveSDKModelShow
     */
    trailers?: Array<any>;
    /**
     *
     * @type {Array&lt;any&gt;}
     * @memberof MassiveSDKModelShow
     */
    vams?: Array<any>;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelShow
     */
    scopes?: Array<string>;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelShow
     */
    categories?: Array<string>;
    /**
     *
     * @type {any}
     * @memberof MassiveSDKModelShow
     */
    customFields?: any;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    customId?: string;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelShow
     */
    genres?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    id?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    type?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    description?: string;
    /**
     *
     * @type {Date}
     * @memberof MassiveSDKModelShow
     */
    maximumOfferEnd?: Date;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    shortDescription?: string;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    contextualTitle?: string;
    /**
     *
     * @type {Array&lt;any&gt;}
     * @memberof MassiveSDKModelShow
     */
    themes?: Array<any>;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    title?: string;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelShow
     */
    totalUserRatings?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelShow
     */
    path?: string;
    /**
     *
     * @type {Array&lt;string&gt;}
     * @memberof MassiveSDKModelShow
     */
    genrePaths?: Array<string>;
    /**
     *
     * @type {MassiveSDKModelSeasons}
     * @memberof MassiveSDKModelShow
     */
    seasons?: MassiveSDKModelSeasons;
}

/**
 *
 * @export
 * @interface MassiveSDKModelTheme
 */
export interface MassiveSDKModelTheme {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelTheme
     */
    type?: MassiveSDKModelTheme.TypeEnum;
    /**
     *
     * @type {Array&lt;MassiveSDKModelThemeColor&gt;}
     * @memberof MassiveSDKModelTheme
     */
    colors?: Array<MassiveSDKModelThemeColor>;
}

/**
 * @export
 * @namespace MassiveSDKModelTheme
 */
export namespace MassiveSDKModelTheme {
    /**
     * @export
     * @enum {string}
     */
    export enum TypeEnum {
        Background = <any> 'Background',
        Text = <any> 'Text',
        Custom = <any> 'Custom'
    }
}

/**
 *
 * @export
 * @interface MassiveSDKModelThemeColor
 */
export interface MassiveSDKModelThemeColor {
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelThemeColor
     */
    name?: string;
    /**
     *
     * @type {number}
     * @memberof MassiveSDKModelThemeColor
     */
    opacity?: number;
    /**
     *
     * @type {string}
     * @memberof MassiveSDKModelThemeColor
     */
    value?: string;
}


/**
 * SearchApi - fetch parameter creator
 * @export
 */
export const SearchApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @param {string} [term]
         * @param {Array&lt;string&gt;} [include]
         * @param {boolean} [group]
         * @param {number} [maxResults]
         * @param {string} [maxRating]
         * @param {string} [device]
         * @param {string} [sub]
         * @param {Array&lt;string&gt;} [segments]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(term?: string, include?: Array<string>, group?: boolean, maxResults?: number, maxRating?: string, device?: string, sub?: string, segments?: Array<string>, options: any = {}): FetchArgs {
            const localVarPath = `/v1/search`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication AWSApiKeyAuth required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("x-api-key")
					: configuration.apiKey;
                localVarHeaderParameter["x-api-key"] = localVarApiKeyValue;
            }

            // authentication JWToken required
            if (configuration && configuration.apiKey) {
                const localVarApiKeyValue = typeof configuration.apiKey === 'function'
					? configuration.apiKey("Authorization")
					: configuration.apiKey;
                localVarHeaderParameter["Authorization"] = localVarApiKeyValue;
            }

            if (term !== undefined) {
                localVarQueryParameter['term'] = term;
            }

            if (include) {
                localVarQueryParameter['include'] = include;
            }

            if (group !== undefined) {
                localVarQueryParameter['group'] = group;
            }

            if (maxResults !== undefined) {
                localVarQueryParameter['maxResults'] = maxResults;
            }

            if (maxRating !== undefined) {
                localVarQueryParameter['maxRating'] = maxRating;
            }

            if (device !== undefined) {
                localVarQueryParameter['device'] = device;
            }

            if (sub !== undefined) {
                localVarQueryParameter['sub'] = sub;
            }

            if (segments) {
                localVarQueryParameter['segments'] = segments;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SearchApi - functional programming interface
 * @export
 */
export const SearchApiFp = function(configuration?: Configuration) {
    return {
        /**
         *
         * @param {string} [term]
         * @param {Array&lt;string&gt;} [include]
         * @param {boolean} [group]
         * @param {number} [maxResults]
         * @param {string} [maxRating]
         * @param {string} [device]
         * @param {string} [sub]
         * @param {Array&lt;string&gt;} [segments]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(term?: string, include?: Array<string>, group?: boolean, maxResults?: number, maxRating?: string, device?: string, sub?: string, segments?: Array<string>, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<BritboxAPISearchModelsSearchGetResponse> {
            const localVarFetchArgs = SearchApiFetchParamCreator(configuration).get(term, include, group, maxResults, maxRating, device, sub, segments, options);
            return (fetch: FetchAPI = portableFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * SearchApi - factory interface
 * @export
 */
export const SearchApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         *
         * @param {string} [term]
         * @param {Array&lt;string&gt;} [include]
         * @param {boolean} [group]
         * @param {number} [maxResults]
         * @param {string} [maxRating]
         * @param {string} [device]
         * @param {string} [sub]
         * @param {Array&lt;string&gt;} [segments]
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(term?: string, include?: Array<string>, group?: boolean, maxResults?: number, maxRating?: string, device?: string, sub?: string, segments?: Array<string>, options?: any) {
            return SearchApiFp(configuration).get(term, include, group, maxResults, maxRating, device, sub, segments, options)(fetch, basePath);
        },
    };
};

/**
 * SearchApi - object-oriented interface
 * @export
 * @class SearchApi
 * @extends {BaseAPI}
 */
export class SearchApi extends BaseAPI {
    /**
     *
     * @param {} [term]
     * @param {} [include]
     * @param {} [group]
     * @param {} [maxResults]
     * @param {} [maxRating]
     * @param {} [device]
     * @param {} [sub]
     * @param {} [segments]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SearchApi
     */
    public get(term?: string, include?: Array<string>, group?: boolean, maxResults?: number, maxRating?: string, device?: string, sub?: string, segments?: Array<string>, options?: any) {
        return SearchApiFp(this.configuration).get(term, include, group, maxResults, maxRating, device, sub, segments, options)(this.fetch, this.basePath);
    }

}

