require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Britbox' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'BritboxTests' do
    inherit! :complete
    # Pods for testing
  end

  # pod 'google-cast-sdk'
  # pod 'react-native-google-cast/NoBluetooth', path: '../node_modules/react-native-google-cast/ios'
  # pod 'google-cast-sdk-no-bluetooth'
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Britbox-tvOS' do
  # Pods for Britbox-tvOS

  target 'Britbox-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
