export const base = {
  FONT_SIZE_TINY: 8,
  FONT_SIZE_SMALL: 10,
  FONT_SIZE_MEDIUM: 14,
  FONT_SIZE_LARGE: 16,
  FONT_SIZE_EXTRA_LARGE: 22,
  FONT_SIZE_MASSIVE: 40,

  FONT_WEIGHT_LIGHT: '300',
  FONT_WEIGHT_MEDIUM: '700',
  FONT_WEIGHT_BOLD: '900',

  PRIMARY_FONT_FAMILY: 'MuseoSans-500',
  PRIMARY_FONT_FAMILY_LIGHT: 'MuseoSans-300',
  PRIMARY_FONT_FAMILY_MEDIUM: 'MuseoSans-700',
  PRIMARY_FONT_FAMILY_BOLD: 'MuseoSans-900',
};

export const darkTheme = {
  PRIMARY_COLOR: '#171b23',
  PRIMARY_TEXT_COLOR_OPAQUE: '#d1d1d1',
  PRIMARY_FOREGROUND_COLOR: '#FFFFFF',
  BACKGROUND_COLOR: '#F5F5F5',

  PRIMARY_TEXT_COLOR: '#000000',
  PRIMARY_TEXT_COLOR_LIGHT: '#F7F7F7',
  PRIMARY_COLOR_OPAQUE: '#323c51',

  SECONDARY_COLOR: '#2d6eff',
  SECONDARY_FOREGROUND_COLOR: '#FFFFFF',
  SECONDARY_COLOR_LIGHT: '#04c3fc',

  ERROR_COLOR: '#F03F3F',
  SUCCESS_COLOR: '#009935',
};

export const lightTheme = {
  PRIMARY_COLOR: '#171b23',
  PRIMARY_TEXT_COLOR_OPAQUE: '#d1d1d1',
  PRIMARY_FOREGROUND_COLOR: '#FFFFFF',
  BACKGROUND_COLOR: '#F5F5F5',

  PRIMARY_TEXT_COLOR: '#FFFFFF',
  PRIMARY_TEXT_COLOR_LIGHT: '#FFFFFF',
  PRIMARY_COLOR_OPAQUE: '#323c51',

  SECONDARY_COLOR: '#2d6eff',
  SECONDARY_FOREGROUND_COLOR: '#FFFFFF',
  SECONDARY_COLOR_LIGHT: '#04c3fc',

  ERROR_COLOR: '#F03F3F',
  SUCCESS_COLOR: '#009935',
};

export const colorOptions = {
  black: {
    PRIMARY_COLOR_BOLD: '#484848',
    PRIMARY_COLOR_FAINT: '#6D7278',
    PRIMARY_COLOR_LIGHT: '#EDEDED',

    SECONDARY_COLOR_BOLD: '#8B8B8B',
    SECONDARY_COLOR_FAINT: '#6D7278',
    SECONDARY_COLOR_LIGHT: '#04c3fc',
  },
};
